# CrashReporter.exp
# CrashReporter
#
# Created by Landon Fuller on 12/5/08.
# Copyright 2008-2011 Plausible Labs Cooperative, Inc. All rights reserved.

# PLCrashReporter
_PLCrashReporterException
_PLCrashReporterErrorDomain

# Export all Objective-C classes; they're picked up by the runtime regardless.
.objc_class_name_PL*
_OBJC_CLASS_$_PL*

# PLCrashReport
_PLCrashReportHostOperatingSystem
_PLCrashReportHostArchitecture
